apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert-staging
  namespace: systems
spec:
  secretName: traefik-cert-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - '*.bibilen.net'
